src = ["src"]
target-version = "py313"

# Group violations by containing file
output-format = "grouped"

fix = true
line-length = 120

exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".github",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "build",
  "dist",
  "node_modules",
  "venv",
  "archive",
  "bazel-*",
]

[lint]
select = [
  "E",    # pycodestyle
  "F",    # pyflakes
  "UP",   # pyupgrade
  "D",    # pydocstyle
  "I001", # import sorting
  "B",    # flake8-bugbear
  "N",    # pep8 naming
  "ISC",  # flake8 implicit string concat
  "PTH",  # flake8-use-pathlib use Path library
  "PD",   # pandas-vet
]

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B", "SIM", "TRY", "RUF"]

[lint.per-file-ignores]
"__init__.py" = [
  "F401", # import unused
]

[lint.pydocstyle]
convention = "google"

# allow unused *args, **kwargs
[lint.flake8-unused-arguments]
ignore-variadic-names = true

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

docstring-code-format = true
